services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blogger-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - .:/workspaces/BloggerWebApp
    networks:
      - bloggerwebapi_blogapp-network

networks:
  bloggerwebapi_blogapp-network:
    external: true
