version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blogger-frontend
    ports:
      - "5013:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
